upcApp.messages = {
WeekDays : ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
wirelessChannelRangeInfo : 'To detect interference from radar systems, the radio will check channel availability for 1 minute.  If a radar system is detected, an alternative channel will be used to avoid co-channel operation',
addNewAlwdDomain : 'Add new allowed domain',
addNewBlckDomain : 'Add new blocked domain',
addNewKword : 'Add new keyword',
cancelLabel : 'Cancel',
saveLabel : 'Save',
securityKeyLabel : 'Security Key',
securityKeyReLabel:'Retype Security Key',
cannotGetAPs: 'Cannot get list of the Access Points',
cannotPerformSearchOrTimeOut : 'Fail to search due to error or time-out.\nIf you press "OK" device will be restarted to save current configuration.',
cannotReleaseIp : 'Cannot release the IP address!\n Please try again later or check your connection!',
cannotRenewIP : 'Cannot renew the IP address!\n Please try again later or check your connection!',
cannotRestart : 'Not able to restart',
cantGetPingID : 'Cannot start Ping process!',
cantGetPolicy : 'Cannot get policy: ',
cantSendRestartCmd : 'Cannot send restart command to the device!',
checkNetwork : 'Check the network configuration <br/> Network name (SSID):',
connSucces : 'Succeed in connect',
errorLabel : 'Error',
refreshLabel : "Refresh",
ethConnectionFound : 'Ethernet connection found.\nThe device must be restarted to save current configuration.\nPress OK to perform the restart.',
forceFreqFailure : 'Forcing frequency failed',
forceFreqSuccess : 'Check downstream status after about 10 seconds',
generalAjaxError : 'Cannot send the request!',
getAPfailed : 'Failed to get AP list. Retry?',
netConnected : 'The network is connected',
networkFail : 'Fail to connect to the network',
networkNameLabel : 'Network name (SSID): ',
newToDPolicyPrompt : 'Please provide name for new ToD policy',
newWebPolicyPrompt : 'Please provide name for new Web Site Filters policy',
okLabel : '&nbsp;OK&nbsp;',
pbcConnEstablishTimeout : 'Fail to establish PBC connection (Timeout)!',
performTheSearch : ' Perform the search ?',
pleaseWait4restart : 'Please wait as the device is being restarted ... ',
policyDefaultNotOK : ['Cannot make policy "', '" default'],
policyDefaultOK : ['Policy "', '" is now default'],
pres3pGW : 'Your settings has been successfully saved. Please press the PBC button on the 3rd party adapter within 2 minutes',
saveSuccess : 'Your setting have been successfully saved',
saveFailure : 'Could not save your settings',
saveTimeout : 'Could not save your settings. Timeout!',
alreadySaved : 'Your settings are already saved',
searchWindowLabel : 'Searching for the connection, please wait...',
waitForSave : 'Your settings are being saved ...',
staAPNotConnected : 'Something\'s wrong. Cannot connect!',
staAPconnected : 'Connected!',
sysRestart : 'Device will be restarted',
timeout	: 'Timeout! Do you want to try it again?',
waitWhileScanning : "Choose Access Point",
wifiParing : 'WiFi Pairing ... ',
wifimanConnectionFound : 'The manually configured WiFi connection has been set!',
wifipbcConnectionFound : 'The PCB WiFi connection has been set!',
wifiscanConnectionFound : 'The WiFi connection has been set!',
wrongFrequency : 'Wrong Frequency!',
wrongIP : 'Wrong IP address!',
wrongPIN : 'Wrong PIN.<br/> It must be 8 digit number.',
wrongKey : 'Wrong key',
wrongMacAddress : 'Wrong MAC Address!',
wrongPassLength: 'The password must be at least 6 and no more than 12 characters long',
wrongPortRange : 'Wrong Port Range!',
WrongPassword : 'Wrong password!',
PasswordConfirmError : 'The new password and the confirm new password do not match.',
addNewPolicyLabel : '&nbsp;&raquo;&nbsp;Create new rule...',
showPassLabel : 'Show password',
apListWindowTitle : 'Access points found',
apConnConfigWindow : 'Configuration of the WiFi connection',
homeNetConfigWindowLabel : 'Configuration of Home Network',
wifiSecConfigWindowLabel : 'Configuration of Wireless Security',
wifiAdvConfigWindowLabel : 'Wireless Advanced Settings',
wifiWpsConfigWindowLabel : 'Configuration of Wireless WPS',
restoreLabel : 'Restore',
restartConfirmationWindowLabel : 'The device must be restarted',
ToDLabel : "ToD Filters",
webFiltersLabel : "Web Site Filters",
connDownStreamLabel : "Connection downstream",
basicInternetLabel : 'Basic Internet Configuration',
restartNeeded : 'Restart is required',
toMuchMan : 'The limit of number of list items is ',
newConfSaved : 'New configuration have been successfully saved',
newPassNotValid : 'The password does not meet minimum & maximum length restrictions',
noFile: 'Please choose a file',
newPassNoMatch : 'New password and its repetition does not match!',
noFileSelected : 'No file was selected!',
AddRowLabel : 'Add row',
limitReached : 'You have reached the limit of defined entries!',
StartPing : 'Start Ping...',
PingAborted : 'Ping Aborted!',
StartTrace : 'Start Trace...',
TraceAborted : 'Tracing Aborted!',
ApName : 'AP name (SSID)',
Channel : 'Channel',
Secure : 'Secure',
Signal : 'Signal',
Success : 'Success',
Failure : 'Failure',
OK : 'OK'
};
