#!/bin/sh

alias ll='ls -l'

top_ver=`cat /etc_ro/top-release`
echo -e "TOP   : $top_ver\n"

if grep rt2860v2 /proc/modules > /dev/null; then
    wlan_ver=`iwpriv ra0 version | sed -e 's/^.*version://'`
    echo "WLAN  : $wlan_ver"
fi

if grep cedrv /proc/modules > /dev/null; then
    cedrv_ver=`iwpriv ce0 version | sed -e 's/^.*version://'`
    echo "CEDRV : $cedrv_ver"
fi

if grep raeth /proc/modules > /dev/null; then
    eth_ver=`cat /sys/module/raeth/parameters/version`
    echo -e "ETH   : $eth_ver\n"
fi

