#!/bin/sh

all_opt="all"
except_opt="not"

usage ()
{
    echo -en "Usage: $0 [option]...\n"
    echo -en "Options:\n\n"
    echo -en " enable  all             : Enable all ports\n"
    echo -en " enable      <port list> : Enable all listed ports\n"
    echo -en " enable  not <port list> : Enable all ports except for listed\n"
    echo -en " disable all             : Disable all ports\n"
    echo -en " disable     <port list> : Disable all listed ports\n"
    echo -en " disable not <port list> : Disable all ports except for listed\n"

    exit 
} >&2

set_port ()
{
    path="/sys/class/net/$1/brport/enable"
    echo "$2" > $path
}

all_ports ()
{
    state=1
    if [ "$1" = "disable" ]; then
        state=0
    fi

    for port in `ls /sys/class/net/`
    do
        if [ -e /sys/class/net/$port/brport ];then
            set_port $port $state
        fi
    done

    sleep 1

    exit
}

all_ports_except_listed ()
{
    state=1
    if [ "$1" = "disable" ];then
        state=0
    fi

    shift

    for port in `ls /sys/class/net/`
    do
        if [ -e /sys/class/net/$port/brport ];then
            skip=0
            for list in "$@" 
            do
                if [ "$port" = "$list" ];then
                    skip=1
                fi
            done

            if [ "$skip" = "0" ];then
                set_port $port $state
            fi
        fi
    done

    sleep 1

    exit
}

listed_ports ()
{
    state=1
    if [ "$1" = "disable" ];then
        state=0
    fi

    shift

    for port in "$@" 
    do
        set_port $port $state
    done 

    sleep 1

    exit
}

if [ "$#" -lt "2" ]; then
    usage
fi

if [ "$1" != "enable" -a "$1" != "disable" ]; then
    usage
fi

action=$1

if [ "$2" = "$all_opt" ]; then
    all_ports $action
fi

if [ "$2" = "$except_opt" ]; then
    if [ "$#" -lt "3" ]; then
        usage
    fi

    shift 2
    all_ports_except_listed $action $*
fi

shift
listed_ports $action $*
