CONFIG_MIPS=y

CONFIG_CONFIG_APP_INIC=y
CONFIG_CONFIG_WLAN_DUAL_CONCURRENT=y

CONFIG_ZONE_DMA=y
CONFIG_RALINK_RT3883_MP=y
CONFIG_RALINK_RT3883=y
CONFIG_RT3883_ASIC=y
CONFIG_PCIE_ONLY=y
CONFIG_RT2880_DRAM_64M=y
CONFIG_MTD_NOR_RALINK=y
CONFIG_RALINK_RAM_SIZE=64
CONFIG_RT2880_ROOTFS_IN_RAM=y
CONFIG_LZMARAMFS=y
CONFIG_RALINK_TIMER_DFS=y
CONFIG_RWSEM_GENERIC_SPINLOCK=y
CONFIG_GENERIC_FIND_NEXT_BIT=y
CONFIG_GENERIC_HWEIGHT=y
CONFIG_GENERIC_CALIBRATE_DELAY=y
CONFIG_GENERIC_TIME=y
CONFIG_SCHED_NO_NO_OMIT_FRAME_POINTER=y
CONFIG_DMA_NONCOHERENT=y
CONFIG_DMA_NEED_PCI_MAP_STATE=y
CONFIG_CPU_LITTLE_ENDIAN=y
CONFIG_SYS_SUPPORTS_LITTLE_ENDIAN=y
CONFIG_IRQ_CPU=y
CONFIG_SWAP_IO_SPACE=y
CONFIG_BOOT_ELF32=y
CONFIG_MIPS_L1_CACHE_SHIFT=5

CONFIG_CPU_MIPS32_R2=y
CONFIG_SYS_HAS_CPU_MIPS32_R1=y
CONFIG_SYS_HAS_CPU_MIPS32_R2=y
CONFIG_CPU_MIPS32=y
CONFIG_CPU_MIPSR2=y
CONFIG_SYS_SUPPORTS_32BIT_KERNEL=y
CONFIG_CPU_SUPPORTS_32BIT_KERNEL=y

CONFIG_32BIT=y
CONFIG_PAGE_SIZE_4KB=y
CONFIG_CPU_HAS_PREFETCH=y
CONFIG_MIPS_MT_DISABLED=y
CONFIG_CPU_HAS_LLSC=y
CONFIG_CPU_HAS_SYNC=y
CONFIG_GENERIC_HARDIRQS=y
CONFIG_GENERIC_IRQ_PROBE=y
CONFIG_CPU_SUPPORTS_HIGHMEM=y
CONFIG_ARCH_FLATMEM_ENABLE=y
CONFIG_SELECT_MEMORY_MODEL=y
CONFIG_FLATMEM_MANUAL=y
CONFIG_FLATMEM=y
CONFIG_FLAT_NODE_MEM_MAP=y
CONFIG_SPLIT_PTLOCK_CPUS=4
CONFIG_ZONE_DMA_FLAG=1
CONFIG_HZ_1000=y
CONFIG_SYS_SUPPORTS_ARBIT_HZ=y
CONFIG_HZ=1000
CONFIG_PREEMPT_NONE=y
CONFIG_LOCKDEP_SUPPORT=y
CONFIG_STACKTRACE_SUPPORT=y
CONFIG_DEFCONFIG_LIST="/lib/modules/$UNAME_RELEASE/.config"

CONFIG_EXPERIMENTAL=y
CONFIG_BROKEN_ON_SMP=y
CONFIG_INIT_ENV_ARG_LIMIT=32

CONFIG_LOCALVERSION=""
CONFIG_SYSVIPC=y
CONFIG_SYSVIPC_SYSCTL=y
CONFIG_BLK_DEV_INITRD=y
CONFIG_INITRAMFS_SOURCE="usr/empty.cpio"
CONFIG_INITRAMFS_ROOT_UID=0
CONFIG_INITRAMFS_ROOT_GID=0
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
CONFIG_SYSCTL=y
CONFIG_EMBEDDED=y
CONFIG_SYSCTL_SYSCALL=y
CONFIG_KALLSYMS=y
CONFIG_PRINTK_FUNC=y
CONFIG_PRINTK=y
CONFIG_SLAB=y
CONFIG_TINY=y
CONFIG_NET_SMALL=y
CONFIG_PANIC=y
CONFIG_FULL_PANIC=y
CONFIG_MEMPOOL=y
CONFIG_INETPEER=y
CONFIG_NET_SK_FILTER=y
CONFIG_NET_DEV_MULTICAST=y
CONFIG_IGMP=y
CONFIG_MAX_SWAPFILES_SHIFT=0
CONFIG_NR_LDISCS=2
CONFIG_MAX_USER_RT_PRIO=100
CONFIG_PDFLUSH=y
CONFIG_BINFMT_ELF_AOUT=y
CONFIG_TINY_SHMEM=y
CONFIG_BASE_SMALL=1

CONFIG_MODULES=y
CONFIG_MODULE_UNLOAD=y


CONFIG_HW_HAS_PCI=y
CONFIG_PCI=y
CONFIG_MMU=y



CONFIG_BINFMT_ELF=y
CONFIG_TRAD_SIGNALS=y


CONFIG_NET=y

CONFIG_PACKET=y
CONFIG_PACKET_MMAP=y
CONFIG_UNIX=y
CONFIG_INET=y
CONFIG_IP_MULTICAST=y
CONFIG_IP_FIB_HASH=y
CONFIG_TCP_CONG_CUBIC=y
CONFIG_DEFAULT_TCP_CONG="cubic"



CONFIG_BRIDGE=y
CONFIG_BRIDGE_IGMP_SNOOPING=y
CONFIG_VLAN_8021Q=m
CONFIG_LLC=y


CONFIG_WIRELESS_EXT=y













CONFIG_NETDEVICES=y



CONFIG_NET_ETHERNET=y
CONFIG_MII=y





CONFIG_NET_RADIO=y



CONFIG_CELENO_DRV=m






CONFIG_RALINK_GPIO=y
CONFIG_RALINK_I2C=y

CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
CONFIG_SERIAL_8250_NR_UARTS=2
CONFIG_SERIAL_8250_RUNTIME_UARTS=2
CONFIG_SERIAL_8250_EXTENDED=y

CONFIG_SERIAL_CORE=y
CONFIG_SERIAL_CORE_CONSOLE=y
CONFIG_UNIX98_PTYS=y


CONFIG_WATCHDOG=y

CONFIG_RALINK_WATCHDOG=y
CONFIG_RALINK_TIMER_WDG_RESET_OUTPUT=y




























CONFIG_PROC_FS=y
CONFIG_PROC_SYSCTL=y
CONFIG_SYSFS=y
CONFIG_RAMFS=y






CONFIG_TRACE_IRQFLAGS_SUPPORT=y
CONFIG_LOG_BUF_SHIFT=14
CONFIG_CROSSCOMPILE=y
CONFIG_CMDLINE="console=ttyS1,57600n8"
CONFIG_UBOOT_CMDLINE=y



CONFIG_BITREVERSE=y
CONFIG_CRC32=y
CONFIG_ZLIB_INFLATE=m
CONFIG_ZLIB_DEFLATE=m
CONFIG_HAS_IOMEM=y
CONFIG_HAS_IOPORT=y

CONFIG_RALINK_RDM=y
CONFIG_RAETH=m
CONFIG_RA_NETWORK_TASKLET_BH=y
CONFIG_RAETH_CHECKSUM_OFFLOAD=y
CONFIG_CELENO_1_100_1000_AN=y
CONFIG_MAC_TO_GIGAPHY_MODE_ADDR=0x07
CONFIG_CELENO_RT3883_INIC=y
CONFIG_RT2860V2_AP=m
CONFIG_RT2860V2_AP_V24_DATA_STRUCTURE=y
CONFIG_RT2860V2_AP_WSC=y
CONFIG_RT2860V2_AP_LLTD=y
CONFIG_RT2860V2_AP_MBSS=y
CONFIG_RT2860V2_AP_IGMP_SNOOP=y
CONFIG_RT2860V2_AP_DFS=y
CONFIG_RT2860V2_AP_INTELLIGENT_RATE_ADAPTION=y
CONFIG_RT2860V2_AP_TXBF=y
CONFIG_RT3090_AP=m
CONFIG_RT3090_AP_WSC=y
CONFIG_RT3090_AP_MBSS=y
CONFIG_RT3090_AP_APCLI=y
CONFIG_RT3090_AP_IGMP_SNOOP=y
CONFIG_RT3090_80211N_DRAFT3=y
CONFIG_RTDEV_PCI=y
CONFIG_RA_NAT_NONE=y

CONFIG_DEFAULTS_RALINK_RT3883=y
CONFIG_CELENO_INIC_MODE=y
CONFIG_DEFSETTING_8M64M=y
CONFIG_COMPILATION_CLASS="tanami"

CONFIG_DEFAULTS_KERNEL_2_6_21=y
CONFIG_CROSS_COMPILER_PATH="/opt/buildroot-gcc342/bin"

CONFIG_VENDOR=Ralink
CONFIG_PRODUCT=RT3883
CONFIG_LINUXDIR=linux-2.6.21.x
CONFIG_LIBCDIR=
CONFIG_LANGUAGE=
