BBV.namespace("orion.templates").BrowseItem=orion.templates.BrowseItem||(function(){var t=[];
t.push("{{#medias}}");
t.push('<li class="grid-item media-item{{#isMediaGroup}} media-group{{/isMediaGroup}}{{#inPlaylist}} in-playlist{{/inPlaylist}}{{#isPlayable}} playable{{/isPlayable}}" data-media-id="{{id}}" {{^isMediaGroup}}data-media-entitlements="{{entitlements}}"{{/isMediaGroup}}>');
t.push('<div class="hover-toggle">');
t.push('<div class="no-hover">');
t.push('<div class="boxart-wrap">');
t.push('<a class="hover-toggle-link boxart-medium{{#getBoxArtMedium}} has-img{{/getBoxArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getBoxArtMedium}}");
t.push('<img data-art-src="{{getBoxArtMedium}}" src="" alt="{{title}}" />');
t.push("{{/getBoxArtMedium}}");
t.push("</a>");
t.push("</div>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push("</p>");
t.push("</div>");
t.push('<div class="hover-box">');
t.push('<div class="overlay-toggle">');
t.push('<div class="thumbnail">');
t.push('<a class="boxart-medium{{#getBoxArtMedium}} has-img{{/getBoxArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getBoxArtMedium}}");
t.push('<img data-art-src="{{getBoxArtMedium}}" src="" alt="{{title}}" />');
t.push('<div class="play"></div>');
t.push("{{/getBoxArtMedium}}");
t.push("</a>");
t.push('<div class="details">');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push("</div>");
t.push("</div>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#hasChildMedia}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{/hasChildMedia}}");
t.push("{{#hasRunDates}}");
t.push('<p class="release-date">');
t.push("{{getRunYears}}");
t.push("</p>");
t.push("{{/hasRunDates}}");
t.push("{{#hasCategories}}");
t.push('<p class="genre">');
t.push("{{{getGenre}}}");
t.push("</p>");
t.push("{{/hasCategories}}");
t.push("</div>");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/medias}}");
return t.join("")
})();
BBV.namespace("orion.templates").BrowseItemWrapper=orion.templates.BrowseItemWrapper||(function(){var BrowseItemWrapper='<ul class="grid-view">{{>items}}</ul>';
return BrowseItemWrapper
})();
BBV.namespace("orion.templates").CardListings=orion.templates.CardListings||(function(){var t=[];
t.push("<ul>");
t.push("{{#listings}}");
t.push("{{#isNewDate}}");
t.push('<li class="date">{{getFormattedDate}}</li>');
t.push("{{/isNewDate}}");
t.push('<li class="listing" data-id="{{listingId}}" >');
t.push('<span class="asset-details">');
t.push('<span class="time">{{getFormattedStartTime}}</span>');
t.push("<div>");
t.push('<span class="title">{{title}}</span>');
t.push('{{#rating}}<span class="rating">{{ratedLabel}} <span class="age-rating"><span class="rating-wrap">{{rating}}</span></span>{{/rating}}</span>');
t.push("</div>");
t.push("</span>");
t.push('<div class="program-details-wrap" >');
t.push('<div class="program-details">');
t.push("{{#getBoxArtMedium}}");
t.push('<div class="media" class="boxart-medium">');
t.push('<img src="{{getBoxArtMedium}}" alt="{{title}}" />');
t.push("</div>");
t.push("{{/getBoxArtMedium}}");
t.push('<div class="details">');
t.push('<div class="description">');
t.push('<h4>"{{secondaryTitle}}"</h4>');
t.push('<p class="season">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push('<p class="channel-details">{{stationTitle}}, {{getFormattedTime}}</p>');
t.push('<p class="info">{{description}}</p>');
t.push("</div>");
t.push('<div class="cta-link"><a href="{{upcomingLink}}#tv">{{#localizeText}}upcoming{{/localizeText}}</a></div>');
t.push('<div class="cta-link"><a href="{{upcomingLink}}#tv">{{#localizeText}}viewAll{{/localizeText}}</a></div>');
t.push("</div>");
t.push("{{#checkIfLiveStream}}");
t.push('<div class="watch-live">');
t.push('<span class="button margin-fix">');
t.push('<a href="#">Watch Live</a>');
t.push("</span>");
t.push("</div>");
t.push("{{/checkIfLiveStream}}");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/listings}}");
t.push("{{^listings}}");
t.push('<li class="listing tba">');
t.push('<span class="asset-details">');
t.push('<span class="title">TBA</span>');
t.push("</span>");
t.push("</li>");
t.push("{{/listings}}");
t.push("</ul>");
return t.join("")
})();
BBV.namespace("orion.templates").DatePicker=orion.templates.DatePicker||(function(){var DatePicker='<ol>{{#dates}}<li><a href="#startDate={{time}}">{{display}}</a></li>{{/dates}}</ol>';
return DatePicker
})();
BBV.namespace("orion.templates").Dialog=orion.templates.Dialog||(function(){var t=[];
t.push('<div class="dialog">');
t.push('<div class="dialog-inner">');
t.push('<div class="dialog-content"></div>');
t.push('<a href="#" class="close-dialog"></a>');
t.push("</div>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").EPGListSummary=orion.templates.EPGListSummary||(function(){var t=[];
t.push("{{#channels}}");
t.push('<dl class="channel-listing{{#hasLiveStream}} live{{/hasLiveStream}}{{#station.isHd}} hd{{/station.isHd}}" id="station-{{station.id}}" data-channel-id="{{id}}" data-station-id="{{station.id}}" data-sort="{{channelNumber}}" data-channel-name="{{station.title}}" data-timestamp="{{timestamp}}" data-categories="{{genres}}">');
t.push('<dt class="network">');
t.push('<div class="live-hd">');
t.push('<span class="live-content"></span>');
t.push('<span class="hd-content"></span>');
t.push("</div>");
t.push('<span class="channel-number">{{channelNumber}}</span>');
t.push('<a class="logo-inactive" href="{{URL}}"><img src="{{images.inactive}}" alt="{{station.title}}" /></a>');
t.push('<a class="logo-active" href="{{URL}}"><img src="{{images.active}}" alt="{{station.title}}" /></a>');
t.push('<span class="favorite"><a href="#favorite" class="icon"></a></span>');
t.push("</dt>");
t.push('<dd class="listings">');
t.push("<ol>");
t.push("{{#station.listings}}");
t.push('<li class="listing{{#genreHighlight}} highlight{{/genreHighlight}}" style="width: {{width}}px;" data-imi="{{imi}}" data-station-id="{{stationId}}" data-listing-id="{{program.id}}-{{imi}}" data-categories="{{genres}}">');
t.push('<span class="asset-details">');
t.push('<span class="title">{{program.title}}</span>');
t.push("{{#rbIsEntitled}}");
t.push('<div class="notifications">');
t.push('<span class="icon record">{{i18n.recordSet}}</span>');
t.push('<span class="icon record-failed">{{i18n.recordFailed}}</span>');
t.push('<span class="icon record-pending">{{i18n.recordPending}}</span>');
t.push('<span class="icon remind">{{i18n.reminder}}</span>');
t.push('<span class="icon remind-failed">{{i18n.reminderFailed}}</span>');
t.push('<span class="icon remind-pending">{{i18n.reminderPending}}</span>');
t.push("</div>");
t.push("{{/rbIsEntitled}}");
t.push("</span>");
t.push("</li>");
t.push("{{/station.listings}}");
t.push("{{^station.listings}}");
t.push('<li class="listing tba" style="width: 100%;">');
t.push('<span class="asset-details">');
t.push('<span class="title">{{i18n.tba}}</span>');
t.push("</span>");
t.push("</li>");
t.push("{{/station.listings}}");
t.push("</ol>");
t.push("</dd>");
t.push("</dl>");
t.push("{{/channels}}");
return t.join("")
})();
BBV.namespace("orion.templates").EPGListDetails=orion.templates.EPGListDetails||(function(){var t=[];
t.push('<div class="program-details-wrap{{#isStarted}} started{{/isStarted}}{{#isEnded}} ended{{/isEnded}}" data-imi="{{imi}}" data-channel-name="{{channelTitle}}" data-channel-id="{{channelId}}" data-listing-id="{{program.id}}-{{imi}}">');
t.push('<span class="close-details"></span>');
t.push('<div class="program-details{{#isLiveStream}} live-stream{{/isLiveStream}}{{#isLocked}} locked{{/isLocked}}">');
t.push("{{#isLiveStream}}");
t.push("{{^isLoggedIn}}");
t.push('<div class="message">');
t.push("<span></span>");
t.push('<p><a href="#" class="sign-in">{{i18n.signIn}}</a></p>');
t.push("</div>");
t.push("{{/isLoggedIn}}");
t.push("{{#isLocked}}");
t.push('<div class="message">');
t.push("<span></span>");
t.push('<p class="subscription-required">{{i18n.subscription}} <strong>{{channelTitle}}</strong> {{i18n.liveRequired}} <a href="{{i18n.learnMoreLink}}" class="learn-more">{{i18n.learnMore}}</a></p>');
t.push("</div>");
t.push("{{/isLocked}}");
t.push("{{^isLocked}}");
t.push('<div class="media mini-player">');
t.push('<img src="{{boxArtMedium}}" alt="{{program.title}}" />');
t.push("</div>");
t.push("{{/isLocked}}");
t.push("{{/isLiveStream}}");
t.push("{{^isLiveStream}}");
t.push("{{#boxArtMedium}}");
t.push('<div class="media" class="boxart-medium has-img">');
t.push('<img src="{{boxArtMedium}}" alt="{{program.title}}" />');
t.push("</div>");
t.push("{{/boxArtMedium}}");
t.push("{{/isLiveStream}}");
t.push('<div class="details">');
t.push('<div class="description">');
t.push("{{#channelOrRbIsEntitled}}");
t.push('<div class="user-functionality">');
t.push("{{#channelIsEntitled}}");
t.push('<span class="button play watch-now"><a href="{{URL}}">{{i18n.watchNow}}</a></span>');
t.push("{{/channelIsEntitled}}");
t.push("{{#rbIsEntitled}}");
t.push('<span class="button watch record"><a href="#">{{i18n.recordButton}}</a></span>');
t.push('<span class="button watch remind"><a href="#">{{i18n.reminderButton}}</a></span>');
t.push('<span class="icon record">{{i18n.recordSet}}</span>');
t.push('<span class="icon record-failed">{{i18n.recordFailed}}</span>');
t.push('<span class="icon record-pending">{{i18n.recordPending}}</span>');
t.push('<span class="icon remind">{{i18n.reminderSet}}</span>');
t.push('<span class="icon remind-failed">{{i18n.reminderFailed}}</span>');
t.push('<span class="icon remind-pending">{{i18n.reminderPending}}</span>');
t.push("{{/rbIsEntitled}}");
t.push("</div>");
t.push("{{/channelOrRbIsEntitled}}");
t.push("<h3>{{program.title}}</h3>");
t.push("{{#program.secondaryTitle}}<h4>{{program.secondaryTitle}}</h4>{{/program.secondaryTitle}}");
t.push('{{#program.seasonNumber}}<p class="season">{{i18n.season}} {{program.seasonNumber}}{{#program.seasonEpisodeNumber}} : {{i18n.episode}} {{program.seasonEpisodeNumber}}{{/program.seasonEpisodeNumber}}</p>{{/program.seasonNumber}}');
t.push('<p class="channel-details">{{channelTitle}}, {{time}}</p>');
t.push("<p>{{program.description}}</p>");
t.push("</div>");
t.push('<div class="cta-link"><a href="{{upcomingLink}}#tv">{{i18n.upcoming}}</a></div>');
t.push("</div>");
t.push("</div>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").FacebookActivity=orion.templates.FacebookActivity||(function(){var t=[];
t.push('<div class="dialog-content" id="facebook">');
t.push('<div class="user-functionality myorionbar-functionality">');
t.push("<h2>{{#localizeText}}recentActivity{{/localizeText}}</h2>");
t.push("</div>");
t.push("{{#template}}");
t.push('<div class="fb-activity" data-site="{{url}}" data-app-id="{{appId}}" data-width="{{width}}" data-height="{{height}}" data-header="{{header}}" data-colorscheme="{{colorScheme}}" data-font="{{font}}" data-recommendations="{{recommendations}}" data-border-color="{{borderColor}}"></div>');
t.push("{{/template}}");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").FeedGridItem=orion.templates.FeedGridItem||(function(){var t=[];
t.push('<ul class="grid-view">');
t.push("{{#medias}}");
t.push('<li class="grid-item media-item{{#isMediaGroup}} media-group{{/isMediaGroup}}{{#inPlaylist}} in-playlist{{/inPlaylist}}{{#isPlayable}} playable{{/isPlayable}}" data-media-id="{{id}}" {{^isMediaGroup}}data-media-entitlements="{{entitlements}}"{{/isMediaGroup}}>');
t.push('<div class="hover-toggle">');
t.push('<div class="no-hover">');
t.push('<a class="hover-toggle-link {{imageType}}{{#getImg}} has-img{{/getImg}}" href="{{buildMediaUrl}}">');
t.push("{{#getImg}}");
t.push('<img src="{{getImg}}" alt="{{title}}" />');
t.push("{{/getImg}}");
t.push("</a>");
t.push("{{#title}}");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{truncatedTitle}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{/title}}");
t.push("{{#secondaryTitle}}");
t.push('<p class="secondary-title">');
t.push('"{{secondaryTitle}}"');
t.push("</p>");
t.push("{{/secondaryTitle}}");
t.push("{{#isMovie}}");
t.push("{{#year}}");
t.push('<p class="release-date">{{getYear}}</p>');
t.push("{{/year}}");
t.push("{{/isMovie}}");
t.push("{{#isEpisode}}");
t.push("{{#seasonNumber}}{{#seasonEpisodeNumber}}");
t.push('<p class="episode-info">');
t.push("{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}");
t.push("</p>");
t.push("{{/seasonEpisodeNumber}}{{/seasonNumber}}");
t.push("{{/isEpisode}}");
t.push("</div>");
t.push('<div class="hover-box">');
t.push('<div class="overlay-toggle">');
t.push('<div class="boxart-wrap">');
t.push('<a class="{{imageType}}{{#getImg}} has-img{{/getImg}}" href="{{buildMediaUrl}}">');
t.push("{{#getImg}}");
t.push('<img src="{{getImg}}" alt="{{title}}" />');
t.push("{{/getImg}}");
t.push('<div class="play"></div>');
t.push("</a>");
t.push('<div class="functionality">');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push("</div>");
t.push("</div>");
t.push("{{#title}}");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{/title}}");
t.push("{{#secondaryTitle}}");
t.push('<p class="secondary-title">');
t.push('"{{secondaryTitle}}"');
t.push("</p>");
t.push("{{/secondaryTitle}}");
t.push("{{#isMediaGroup}}");
t.push("{{#hasChildMedia}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{/hasChildMedia}}");
t.push("{{#hasRunDates}}");
t.push('<p class="release-date">');
t.push("{{getRunYears}}");
t.push("</p>");
t.push("{{/hasRunDates}}");
t.push("{{/isMediaGroup}}");
t.push("{{#isEpisode}}");
t.push("{{#seasonNumber}}{{#seasonEpisodeNumber}}");
t.push('<p class="episode-info">');
t.push("{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}");
t.push("</p>");
t.push("{{/seasonEpisodeNumber}}{{/seasonNumber}}");
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push('{{#formatLength}}<p class="run-time">({{formatLength}})</p>{{/formatLength}}');
t.push("{{/isEpisode}}");
t.push("{{#isMovieItem}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push("{{/isMovieItem}}");
t.push("{{#hasCategories}}");
t.push('<p class="genre">');
t.push("{{{getGenre}}}");
t.push("</p>");
t.push("{{/hasCategories}}");
t.push("</div>");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
return t.join("")
})();
BBV.namespace("orion.templates").FeedListItem=orion.templates.FeedListItem||(function(){var t=[];
t.push('<ul class="list-view">');
t.push('<li class="header">');
t.push('<span class="title">{{#localizeText}}titleheading{{/localizeText}}</span>');
t.push('<span class="rating">{{#localizeText}}ratedheading{{/localizeText}}</span>');
t.push('<span class="genre">{{#localizeText}}genreheading{{/localizeText}}</span>');
t.push('<span class="release-date">{{#localizeText}}releaseheading{{/localizeText}}</span>');
t.push('<span class="add"></span>');
t.push("</li>");
t.push("{{#medias}}");
t.push('<li class="media-item{{#isMediaGroup}} media-group{{/isMediaGroup}}{{#inPlaylist}} in-playlist{{/inPlaylist}}" data-media-id="{{id}}" {{^isMediaGroup}}data-media-entitlements="{{entitlements}}"{{/isMediaGroup}}>');
t.push('<span class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a> {{#formatLength}}<span class="run-time">({{formatLength}})</span>{{/formatLength}}');
t.push("</span>");
t.push('<span class="rating">{{highestParentalRating}}</span>');
t.push('<span class="genre">{{{getGenre}}}</span>');
t.push('<span class="release-date">{{getFormattedDate}}</span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
return t.join("")
})();
BBV.namespace("orion.templates").FeedThumbItem=orion.templates.FeedThumbItem||(function(){var t=[];
t.push('<ul class="grid-view thumbnails">');
t.push("{{#medias}}");
t.push('<li class="grid-item media-item{{#isMediaGroup}} media-group{{/isMediaGroup}}{{#inPlaylist}} in-playlist{{/inPlaylist}}{{#isPlayable}} playable{{/isPlayable}}" data-media-id="{{id}}" {{^isMediaGroup}}data-media-entitlements="{{entitlements}}"{{/isMediaGroup}}>');
t.push('<div class="hover-toggle">');
t.push('<div class="no-hover">');
t.push('<a class="hover-toggle-link {{imageType}}{{#getImg}} has-img{{/getImg}}" href="{{buildMediaUrl}}">');
t.push("{{#getImg}}");
t.push('<img src="{{getImg}}" alt="{{title}}" />');
t.push("{{/getImg}}");
t.push("</a>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#isMovie}}");
t.push("{{#year}}");
t.push('<p class="release-date">{{getYear}}</p>');
t.push("{{/year}}");
t.push("{{/isMovie}}");
t.push("{{#isEpisode}}");
t.push("{{#secondaryTitle}}");
t.push('<p class="episode-info">');
t.push('"{{secondaryTitle}}"');
t.push("</p>");
t.push("{{/secondaryTitle}}");
t.push('<p class="episode-info">');
t.push("{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}");
t.push("</p>");
t.push("{{/isEpisode}}");
t.push("</div>");
t.push('<div class="hover-box">');
t.push('<div class="overlay-toggle">');
t.push('<div class="boxart-wrap">');
t.push('<a class="{{imageType}}{{#getImg}} has-img{{/getImg}}" href="{{buildMediaUrl}}">');
t.push("{{#getImg}}");
t.push('<img src="{{getImg}}" alt="{{title}}" />');
t.push("{{/getImg}}");
t.push('<div class="play"></div>');
t.push("</a>");
t.push('<div class="functionality">');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push("</div>");
t.push("</div>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#isMediaGroup}}");
t.push("{{#hasChildMedia}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{/hasChildMedia}}");
t.push("{{#hasRunDates}}");
t.push('<p class="release-date">');
t.push("{{getRunYears}}");
t.push("</p>");
t.push("{{/hasRunDates}}");
t.push("{{/isMediaGroup}}");
t.push("{{#isEpisode}}");
t.push('<p class="episode-info">');
t.push("{{#secondaryTitle}}");
t.push('"{{secondaryTitle}}"');
t.push("</p>");
t.push("{{/secondaryTitle}}");
t.push('{{#formatLength}}<p class="run-time">({{formatLength}})</p>{{/formatLength}}');
t.push('<p class="episode-info">');
t.push("{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}");
t.push("</p>");
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push("{{/isEpisode}}");
t.push("{{#isMovieItem}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push("{{/isMovieItem}}");
t.push("{{#hasCategories}}");
t.push('<p class="genre">');
t.push("{{{getGenre}}}");
t.push("</p>");
t.push("{{/hasCategories}}");
t.push("</div>");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
return t.join("")
})();
BBV.namespace("orion.templates").Offers=orion.templates.Offers||(function(){var t=[];
t.push('<ul class="offers-list">');
t.push("{{#products}}");
t.push('<li class="offer">');
t.push('<div class="offer-text">');
t.push('<h1 class="offer-title">{{name}}</h1>');
t.push('<p class="offer-description"><span class="cost">{{{currency}}} {{^price}} 0{{/price}}{{#price}} {{price}}{{/price}}</span> {{i18n_for}} {{rentalDuration}}</p>');
t.push("</div>");
t.push('<span class="button offer-buy-button"><a href="#" class="offer-button-link" data-product-id="{{productId}}" data-offer-id="{{offerId}}">{{i18n_buy}}</a></span>');
t.push("</li>");
t.push("{{/products}}");
t.push("</ul>");
t.push("{{#show_login_button}}");
t.push('<p><span class="button offer-buy-button{{#not_entitled}} disabled{{/not_entitled}}"><a href="#" class="offer-button-login">{{i18n_buy}}</a></span></p>');
t.push("{{/show_login_button}}");
t.push('<div class="about">');
t.push("    <h1>{{i18n_offers_head}}</h1>");
t.push("    <p>{{{i18n_offers_text}}}</p>");
t.push('    {{#i18n_offers_link}}<p><a class="{{#show_login_button}}offer-button-login{{/show_login_button}}{{^show_login_button}}learn-more{{/show_login_button}}" href="{{offers_link}}">{{i18n_offers_link}}</a></p>{{/i18n_offers_link}}');
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").MyOrionBarDialogWrapper=orion.templates.MyOrionBarDialogWrapper||(function(){var t=[];
t.push('<div class="dialog down myorionbar-dialog" id="myorionbar-dialog">');
t.push('<div class="dialog-inner">');
t.push('<a href="#" class="close-dialog">x</a>');
t.push('<div id="dialog-arrow"></div>');
t.push("</div>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").PlaylistWrapper=orion.templates.PlaylistWrapper||(function(){var t=[];
t.push('<div class="dialog-content" id="playlist">');
t.push("{{>PlaylistBody}}");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").PlaylistStructure=orion.templates.PlaylistStructure||(function(){var t=[];
t.push('<div class="confirmation delete-confirmation sort-confirmation">');
t.push('<div class="dialog">');
t.push("<div>");
t.push('<h2>{{#localizeText}}preReorderText{{/localizeText}} <span id="method"></span></h2>');
t.push("<p>{{#localizeText}}reorderQuestion{{/localizeText}}</p>");
t.push('<span class="button option"><a href="#">{{#localizeText}}reorderConfirm{{/localizeText}}</a></span>');
t.push('<span class="cancel-sort option"><a href="#">{{#localizeText}}cancel{{/localizeText}}</a></span>');
t.push("</div>");
t.push('<a class="close-alt" href="">Close</a>');
t.push("</div>");
t.push("</div>");
t.push('<div class="user-functionality myorionbar-functionality">');
t.push('<ul class="view-toggle medium-toggle">');
t.push("<li>{{#localizeText}}view{{/localizeText}}</li>");
t.push('<li><a href="#all" class="active">{{#localizeText}}all{{/localizeText}} ({{#counts}}{{all}}{{/counts}})</a></li>');
t.push('<li><a href="#tv">{{#localizeText}}tv{{/localizeText}} ({{#counts}}{{tv}}{{/counts}})</a></li>');
t.push('<li><a href="#movie">{{#localizeText}}movies{{/localizeText}} ({{#counts}}{{movie}}{{/counts}})</a></li>');
t.push("</ul>");
t.push("{{#isDialog}}");
t.push('<span class="button">');
t.push('<a href="{{manageUrl}}">{{#localizeText}}managePlaylist{{/localizeText}}</a>');
t.push("</span>");
t.push("{{/isDialog}}");
t.push("{{^isDialog}}");
t.push('<span class="button">');
t.push('<a href="#" id="clear-playlist">{{#localizeText}}clearAllVideos{{/localizeText}}</a>');
t.push("</span>");
t.push("{{/isDialog}}");
t.push("</div>");
t.push('<div class="user-functionality myorionbar-sub-functionality">');
t.push('<div class="sort-playlist">');
t.push('<div class="sort">{{#localizeText}}reorderBy{{/localizeText}}: <span>{{#localizeText}}titleheading{{/localizeText}}</span></div>');
t.push('<div class="select">');
t.push("<ol>");
t.push('<li class="select-title"><a href="#">{{#localizeText}}titleheading{{/localizeText}}</a></li>');
t.push('<li class="select-air-date"><a href="#">{{#localizeText}}airDate{{/localizeText}}</a></li>');
t.push('<li class="select-expiration-date"><a href="#">{{#localizeText}}expirationDate{{/localizeText}}</a></li>');
t.push("</ol>");
t.push("</div>");
t.push("</div>");
t.push('<ul class="view-toggle">');
t.push("<li>{{#localizeText}}viewAs{{/localizeText}} </li>");
t.push('<li class="grid"><a href="#grid-view" class="active">{{#localizeText}}grid{{/localizeText}}</a></li>');
t.push('<li class="list"><a href="#list-view">{{#localizeText}}list{{/localizeText}}</a></li>');
t.push("</ul>");
t.push("</div>");
t.push('<div class="content-list">');
t.push('<ul class="grid-view thumbnails">');
t.push("{{>mediaItemsGrid}}");
t.push("</ul>");
t.push("{{^isDialog}}");
t.push('<ul class="list-view">');
t.push('<li class="header">');
t.push('<div class="title">{{#localizeText}}titleheading{{/localizeText}}</div>');
t.push('<div class="rated">{{#localizeText}}ratedheading{{/localizeText}}</div>');
t.push('<div class="genre">{{#localizeText}}genreheading{{/localizeText}}</div>');
t.push('<div class="air-date">{{#localizeText}}airDate{{/localizeText}}</div>');
t.push("</li>");
t.push("{{>mediaItemsList}}");
t.push("</ul>");
t.push("{{/isDialog}}");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").PlaylistEmpty=orion.templates.PlaylistEmpty||(function(){var t=[];
t.push('<div class="empty">');
t.push("<h2><span>+</span> {{#localizeText}}playlistEmpty{{/localizeText}}</h2>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").PlaylistFull=orion.templates.PlaylistFull||(function(){var t=[];
t.push('<div class="full">');
t.push("<h2>{{#localizeText}}playlistFull{{/localizeText}}</h2>");
t.push("{{#isDialog}}");
t.push('<p><a href="{{manageUrl}}">{{#localizeText}}managePlaylist{{/localizeText}}</a> {{#localizeText}}remove{{/localizeText}} <a href="#" class="cancel">{{#localizeText}}cancel{{/localizeText}}</a>.</p>');
t.push("{{/isDialog}}");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").PlaylistGridItem=orion.templates.PlaylistGridItem||(function(){var t=[];
t.push("{{#template}}");
t.push('<li id="playlist-grid-item-{{id}}" class="media-item grid-item {{#lowerCase}}medium{{/lowerCase}}{{#isPlayable}} playable{{/isPlayable}}" data-media-id="{{id}}">');
t.push('<div class="hover-toggle">');
t.push('<div class="no-hover">');
t.push('<div class="thumbnail">');
t.push('<a class="still-medium{{#getStillArtMedium}} has-img{{/getStillArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getStillArtMedium}}");
t.push('<img src="{{getStillArtMedium}}" alt="{{title}}" />');
t.push("{{/getStillArtMedium}}");
t.push('<span class="order">{{order}}</span>');
t.push("</a>");
t.push("</div>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a></p>');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#isTV}}");
t.push('{{#secondaryTitle}}<p class="episode">"{{secondaryTitle}}"</p>{{/secondaryTitle}}');
t.push('<p class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push("{{/isTV}}");
t.push("{{#isMovie}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/isMovie}}");
t.push('{{#getFormattedPlaylistExpirationDate}}<p class="notification">{{#localizeText}}expiration{{/localizeText}} {{getFormattedPlaylistExpirationDate}}</p>{{/getFormattedPlaylistExpirationDate}}');
t.push('<div class="highlight"></div>');
t.push("</div>");
t.push('<div class="hover-box">');
t.push('<div class="overlay-toggle">');
t.push('<div class="thumbnail">');
t.push('<a class="still-medium{{#getStillArtMedium}} has-img{{/getStillArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getStillArtMedium}}");
t.push('<img src="{{getStillArtMedium}}" alt="{{title}}" />');
t.push("{{/getStillArtMedium}}");
t.push('<div class="play"></div>');
t.push("</a>");
t.push('<div class="details">');
t.push('{{#formatLength}}<span class="run-time">{{formatLength}}</span>{{/formatLength}}');
t.push('<a href="#" class="remove">&ndash;</a>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push("</div>");
t.push("</div>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a>');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#isTV}}");
t.push('{{#secondaryTitle}}<p class="episode">"{{secondaryTitle}}"</p>{{/secondaryTitle}}');
t.push('<p class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push("{{/isTV}}");
t.push("{{#isMovie}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/isMovie}}");
t.push('{{#getFormattedPlaylistExpirationDate}}<p class="notification">{{#localizeText}}expiration{{/localizeText}} {{getFormattedPlaylistExpirationDate}}</p>{{/getFormattedPlaylistExpirationDate}}');
t.push('<div class="highlight"></div>');
t.push("</div>");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/template}}");
return t.join("")
})();
BBV.namespace("orion.templates").PlaylistListItem=orion.templates.PlaylistListItem||(function(){var t=[];
t.push("{{#template}}");
t.push('<li id="playlist-list-item-{{id}}" class="media-item {{#lowerCase}}medium{{/lowerCase}}" data-media-id="{{id}}">');
t.push('<div class="order">#.</div>');
t.push('<div class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}{{#isTV}}{{#secondaryTitle}}: <span class="episode">("{{secondaryTitle}}")</span>{{/secondaryTitle}}{{/isTV}}</a>');
t.push('{{#isTV}}<span class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</span>{{/isTV}}');
t.push('{{#formatLength}}<span class="run-time">({{formatLength}})</span>{{/formatLength}}');
t.push("</div>");
t.push('<div class="rated">{{parentalRating}}</div>');
t.push('<div class="genre">');
t.push("{{{getGenre}}}");
t.push("</div>");
t.push('<div class="air-date">{{getFormattedAirDate}}</div>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push('<div class="highlight"></div>');
t.push("</li>");
t.push("{{/template}}");
return t.join("")
})();
BBV.namespace("orion.templates").RecentlyViewedWrapper=orion.templates.RecentlyViewedWrapper||(function(){var t=[];
t.push('<div class="dialog-content" id="recently-viewed">');
t.push('<div class="user-functionality myorionbar-functionality">');
t.push("<h2>{{#localizeText}}recentlyViewedVideos{{/localizeText}} ({{count}})</h2>");
t.push('<span class="button">');
t.push('<a href="#" id="clear-recent">{{#localizeText}}clearHistory{{/localizeText}}</a>');
t.push("</span>");
t.push("</div>");
t.push("{{>RecentlyViewedBody}}");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").RecentlyViewedBody=orion.templates.RecentlyViewedBody||(function(){var t=[];
t.push('<div class="content-list">');
t.push('<ul class="grid-view thumbnails">');
t.push("{{#template}}");
t.push('<li class="media-item grid-item {{#lowerCase}}medium{{/lowerCase}}{{#isPlayable}} playable{{/isPlayable}}" data-media-id="{{id}}">');
t.push('<div class="hover-toggle">');
t.push('<div class="no-hover">');
t.push('<div class="thumbnail">');
t.push('<a class="still-medium{{#getStillArtMedium}} has-img{{/getStillArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getStillArtMedium}}");
t.push('<img src="{{getStillArtMedium}}" alt="{{title}}" />');
t.push("{{/getStillArtMedium}}");
t.push("</a>");
t.push("</div>");
t.push('<p class="title"><a href="{{buildMediaUrl}}">{{title}}</a></p>');
t.push("{{#isTV}}");
t.push('{{#secondaryTitle}}<p class="episode">"{{secondaryTitle}}"</p>{{/secondaryTitle}}');
t.push('<p class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push("{{/isTV}}");
t.push("{{#isMovie}}");
t.push('<p class="release-date">{{year}}</p>');
t.push('{{#isExpiring}}<p class="notification">{{#localizeText}}expiration{{/localizeText}}</p>{{/isExpiring}}');
t.push("{{/isMovie}}");
t.push("</div>");
t.push('<div class="hover-box">');
t.push('<div class="overlay-toggle">');
t.push('<div class="thumbnail">');
t.push('<a class="still-medium{{#getStillArtMedium}} has-img{{/getStillArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getStillArtMedium}}");
t.push('<img src="{{getStillArtMedium}}" alt="{{title}}" />');
t.push("{{/getStillArtMedium}}");
t.push('<div class="play"></div>');
t.push("</a>");
t.push('<div class="details">');
t.push('{{#formatLength}}<span class="run-time">{{formatLength}}</span>{{/formatLength}}');
t.push("</div>");
t.push("</div>");
t.push('<p class="title"><a href="{{buildMediaUrl}}">{{title}}</a></p>');
t.push("{{#isTV}}");
t.push('{{#secondaryTitle}}<p class="episode">"{{secondaryTitle}}"</p>{{/secondaryTitle}}');
t.push('<p class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push("{{/isTV}}");
t.push("{{#isMovie}}");
t.push('<p class="release-date">{{year}}</p>');
t.push('{{#isExpiring}}<p class="notification">{{#localizeText}}expiration{{/localizeText}}</p>{{/isExpiring}}');
t.push("{{/isMovie}}");
t.push("</div>");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/template}}");
t.push("</ul>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").RecommendationsWrapper=orion.templates.RecommendationsWrapper||(function(){var t=[];
t.push('<div class="dialog-content" id="recommendations">');
t.push('<div class="user-functionality myorionbar-functionality">');
t.push('<h2>{{#localizeText}}recommendations{{/localizeText}} (<span class="count">{{count}}</span>)</h2>');
t.push("</div>");
t.push('<div class="user-functionality myorionbar-sub-functionality">');
t.push('<ul class="view-toggle">');
t.push("<li>{{#localizeText}}viewAs{{/localizeText}}:</li>");
t.push('<li class="grid"><a href="#grid-view" class="active">{{#localizeText}}grid{{/localizeText}}</a></li>');
t.push('<li class="list"><a href="#list-view">{{#localizeText}}list{{/localizeText}}</a></li>');
t.push("</ul>");
t.push("</div>");
t.push("{{>RecommendationsBody}}");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").RecommendationsBody=orion.templates.RecommendationsBody||(function(){var t=[];
t.push('<div class="content-list">');
t.push('<ul class="grid-view thumbnails">');
t.push("{{#medias}}");
t.push('<li class="grid-item media-item {{#isPlayable}} playable{{/isPlayable}}{{#isMediaGroup}} media-group{{/isMediaGroup}}{{#inPlaylist}} in-playlist{{/inPlaylist}}" data-media-id="{{id}}">');
t.push('<div class="hover-toggle">');
t.push('<div class="no-hover">');
t.push('<div class="thumbnail">');
t.push('<a class="still-medium{{#getStillArtMedium}} has-img{{/getStillArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getStillArtMedium}}");
t.push('<img src="{{getStillArtMedium}}" alt="{{title}}" />');
t.push("{{/getStillArtMedium}}");
t.push("</a>");
t.push("</div>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#isMovie}}");
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push("{{/isMovie}}");
t.push("{{#isEpisode}}");
t.push('{{#secondaryTitle}}<p class="episode-info">"{{secondaryTitle}}"</p>{{/secondaryTitle}}');
t.push('<p class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push("{{/isEpisode}}");
t.push("</div>");
t.push('<div class="hover-box">');
t.push('<div class="overlay-toggle">');
t.push('<div class="thumbnail">');
t.push('<a class="still-medium{{#getStillArtMedium}} has-img{{/getStillArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getStillArtMedium}}");
t.push('<img src="{{getStillArtMedium}}" alt="{{title}}" />');
t.push("{{/getStillArtMedium}}");
t.push('<div class="play"></div>');
t.push("</a>");
t.push('<div class="functionality">');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push("</div>");
t.push("</div>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#isMediaGroup}}");
t.push("{{#hasChildMedia}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{/hasChildMedia}}");
t.push("{{#hasRunDates}}");
t.push('<p class="release-date">');
t.push("{{getRunYears}}");
t.push("</p>");
t.push("{{/hasRunDates}}");
t.push("{{/isMediaGroup}}");
t.push("{{#isEpisode}}");
t.push('{{#secondaryTitle}}<p class="episode-info">"{{secondaryTitle}}"</p>{{/secondaryTitle}}');
t.push('<p class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push('{{#formatLength}}<p class="run-time">({{formatLength}})</p>{{/formatLength}}');
t.push("{{/isEpisode}}");
t.push("{{#isMovieItem}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push("{{/isMovieItem}}");
t.push("{{#hasCategories}}");
t.push('<p class="genre">');
t.push("{{{getGenre}}}");
t.push("</p>");
t.push("{{/hasCategories}}");
t.push("</div>");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
t.push('<ul class="list-view">');
t.push('<li class="header">');
t.push('<div class="title">{{#localizeText}}titleheading{{/localizeText}}</div>');
t.push('<div class="rated">{{#localizeText}}ratedheading{{/localizeText}}</div>');
t.push('<div class="genre">{{#localizeText}}genreheading{{/localizeText}}</div>');
t.push('<div class="air-date">{{#localizeText}}airDate{{/localizeText}}</div>');
t.push("</li>");
t.push("{{#medias}}");
t.push('<li class="media-item{{#isMediaGroup}} media-group{{/isMediaGroup}}{{#inPlaylist}} in-playlist{{/inPlaylist}}" data-media-id="{{id}}">');
t.push('<div class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}{{#isTV}}{{#secondaryTitle}}: <span class="episode">("{{secondaryTitle}}")</span>{{/secondaryTitle}}{{/isTV}}</a>');
t.push('{{#isTV}}<span class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</span>{{/isTV}}');
t.push('{{#formatLength}}<span class="run-time">({{formatLength}})</span>{{/formatLength}}');
t.push("</div>");
t.push('<div class="rated">{{parentalRating}}</div>');
t.push('<div class="genre">');
t.push("{{{getGenre}}}");
t.push("</div>");
t.push('<div class="air-date">{{getFormattedAirDate}}</div>');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").MyRentalsWrapper=orion.templates.MyRentalsWrapper||(function(){var t=[];
t.push('<div class="dialog-content" id="my-rentals">');
t.push('<div class="user-functionality myorionbar-functionality">');
t.push("<h2>{{count}} {{#localizeText}}activeRentals{{/localizeText}}</h2>");
t.push('<span class="button">');
t.push('<a href="{{manageUrl}}">{{#localizeText}}manageMyRentals{{/localizeText}}</a>');
t.push("</span>");
t.push("</div>");
t.push('<div class="user-functionality myorionbar-sub-functionality">');
t.push('<ul class="view-toggle">');
t.push("<li>{{#localizeText}}viewAs{{/localizeText}}:</li>");
t.push('<li class="grid"><a href="#grid-view" class="active">{{#localizeText}}grid{{/localizeText}}</a></li>');
t.push('<li class="list"><a href="#list-view">{{#localizeText}}list{{/localizeText}}</a></li>');
t.push("</ul>");
t.push("</div>");
t.push("{{>MyRentalsBody}}");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").MyRentalsBody=orion.templates.MyRentalsBody||(function(){var t=[];
t.push('<div class="content-list">');
t.push('<ul class="grid-view thumbnails">');
t.push("{{#template}}");
t.push('<li class="media-item grid-item {{#lowerCase}}medium{{/lowerCase}}{{#inPlaylist}} in-playlist{{/inPlaylist}}{{#isPlayable}} playable{{/isPlayable}}" data-media-id="{{id}}">');
t.push('<div class="hover-toggle">');
t.push('<div class="no-hover">');
t.push('<div class="thumbnail">');
t.push('<a class="still-medium{{#getStillArtMedium}} has-img{{/getStillArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getStillArtMedium}}");
t.push('<img src="{{getStillArtMedium}}" alt="{{title}}" />');
t.push("{{/getStillArtMedium}}");
t.push("</a>");
t.push("</div>");
t.push('<p class="title"><a href="{{buildMediaUrl}}">{{title}}</a></p>');
t.push("{{#isTV}}");
t.push('{{#secondaryTitle}}<p class="episode">"{{secondaryTitle}}"</p>{{/secondaryTitle}}');
t.push('<p class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push("{{/isTV}}");
t.push("{{#isMovie}}");
t.push('<p class="release-date">{{year}}</p>');
t.push('{{#isProductExpiring}}<p class="notification">{{#localizeText}}expiration{{/localizeText}}</p>{{/isProductExpiring}}');
t.push("{{/isMovie}}");
t.push("<p>{{#localizeText}}availableUntil{{/localizeText}} {{getFormattedProductExpirationDate}}</p>");
t.push("</div>");
t.push('<div class="hover-box">');
t.push('<div class="overlay-toggle">');
t.push('<div class="thumbnail">');
t.push('<a class="still-medium{{#getStillArtMedium}} has-img{{/getStillArtMedium}}" href="{{buildMediaUrl}}">');
t.push("{{#getStillArtMedium}}");
t.push('<img src="{{getStillArtMedium}}" alt="{{title}}" />');
t.push("{{/getStillArtMedium}}");
t.push('<div class="play"></div>');
t.push("</a>");
t.push('<div class="details">');
t.push('{{#formatLength}}<span class="run-time">{{formatLength}}</span>{{/formatLength}}');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push("</div>");
t.push("</div>");
t.push('<p class="title"><a href="{{buildMediaUrl}}">{{title}}</a></p>');
t.push("{{#isTV}}");
t.push('{{#secondaryTitle}}<p class="episode">"{{secondaryTitle}}"</p>{{/secondaryTitle}}');
t.push('<p class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</p>');
t.push("{{/isTV}}");
t.push("{{#isMovie}}");
t.push('<p class="release-date">{{year}}</p>');
t.push('{{#isProductExpiring}}<p class="notification">{{#localizeText}}expiration{{/localizeText}}</p>{{/isProductExpiring}}');
t.push("{{/isMovie}}");
t.push("<p>{{#localizeText}}availableUntil{{/localizeText}} {{getFormattedProductExpirationDate}}</p>");
t.push("</div>");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/template}}");
t.push("</ul>");
t.push('<ul class="list-view">');
t.push('<li class="header">');
t.push('<div class="title">{{#localizeText}}titleheading{{/localizeText}}</div>');
t.push('<div class="rated">{{#localizeText}}ratedheading{{/localizeText}}</div>');
t.push('<div class="genre">{{#localizeText}}genreheading{{/localizeText}}</div>');
t.push('<div class="air-date">{{#localizeText}}expirationDate{{/localizeText}}</div>');
t.push("</li>");
t.push("{{#template}}");
t.push('<li class="media-item {{#lowerCase}}medium{{/lowerCase}}{{#inPlaylist}} in-playlist{{/inPlaylist}}" data-media-id="{{id}}">');
t.push('<div class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}{{#isTV}}{{#secondaryTitle}}: <span class="episode">("{{secondaryTitle}}")</span>{{/secondaryTitle}}{{/isTV}}</a>');
t.push('{{#isTV}}<span class="episode-info">{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}</span>{{/isTV}}');
t.push('{{#formatLength}}<span class="run-time">({{formatLength}})</span>{{/formatLength}}');
t.push("</div>");
t.push('<div class="rated">{{parentalRating}}</div>');
t.push('<div class="genre">');
t.push("{{{getGenre}}}");
t.push("</div>");
t.push('<div class="air-date">{{getFormattedProductExpirationDate}}</div>');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push("</li>");
t.push("{{/template}}");
t.push("</ul>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").RentalTime=orion.templates.RentalTime||(function(){var t=[];
t.push('<div id="tvod-rental-time">');
t.push("<p>{{rental_message}} ");
t.push("{{rental_time}}</p>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").SearchResultsOnline=orion.templates.SearchResultsOnline||(function(){var t=[];
t.push('<div class="results-list content-list online-results">');
t.push('<ul class="list-view">');
t.push("{{#medias}}");
t.push("{{#mediaGroup}}");
t.push("<li>");
t.push('<div class="box-art boxart-small {{#getBoxArtSmall}} has-img{{/getBoxArtSmall}}">');
t.push("{{#getBoxArtSmall}}");
t.push('<img src="{{getBoxArtSmall}}" alt="{{title}}" />');
t.push("{{/getBoxArtSmall}}");
t.push("</div>");
t.push('<div class="description">');
t.push('<p class="title">');
t.push("<strong>{{title}}</strong>");
t.push("{{#hasChildMedia}}<span>{{getChildMedias}}</span>{{/hasChildMedia}}");
t.push("<span>");
t.push("{{#hasRunDates}}{{getRunYears}}{{/hasRunDates}} {{#hasRunDates}} | {{/hasRunDates}}");
t.push("{{#hasParentalRating}}{{highestParentalRating}}{{/hasParentalRating}} {{#hasParentalRating}} | {{/hasParentalRating}}");
t.push("{{#hasCategories}}{{{getGenre}}}{{/hasCategories}}");
t.push("</span>");
t.push("</p>");
t.push("<p>{{description}}</p>");
t.push("</div>");
t.push("{{/mediaGroup}}");
t.push('<div class="grouped-media-items">');
t.push("{{#mediaItems}}");
t.push("{{#isFirstItem}}<ul>{{/isFirstItem}}");
t.push("{{{hiddenStart}}}");
t.push('<li class="media-item" {{^isMediaGroup}}data-media-entitlements="{{entitlements}}"{{/isMediaGroup}}>');
t.push('<div class="media-title">');
t.push("");
t.push("<p>");
t.push("<strong>{{title}}</strong>");
t.push("<span>{{#isTV}} {{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}} {{/isTV}} {{#formatLength}} ({{formatLength}}) {{/formatLength}}</span>");
t.push("</p>");
t.push("</div>");
t.push('<div class="aside">');
t.push('<span class="button"><a href="{{buildMediaUrl}}" class="play">{{#localizeText}}watchNow{{/localizeText}}</a></span>');
t.push("</div>");
t.push('<div class="notifications">');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push("</div>");
t.push("</li>");
t.push("{{{hiddenEnd}}}");
t.push("{{#isLastItem}}");
t.push("</ul>");
t.push("{{#isExpandable}}");
t.push('<div class="show-more">');
t.push('<p><a href="#" data-text-expand="{{#localizeText}}viewAll{{/localizeText}}" data-text-collapse="{{#localizeText}}hideAll{{/localizeText}}"><span class="toggler">{{#localizeText}}viewAll{{/localizeText}}</span> {{groupTitle}} <span class="icon"></span></a></p>');
t.push("</div>");
t.push("{{/isExpandable}}");
t.push("{{/isLastItem}}");
t.push("{{/mediaItems}}");
t.push("</div>");
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").SearchResultsTv=orion.templates.SearchResultsTv||(function(){var t=[];
t.push('<div class="results-list content-list tv-results">');
t.push('<ul class="list-view">');
t.push("{{#medias}}");
t.push("{{#mediaGroup}}");
t.push("<li>");
t.push('<div class="box-art boxart-small {{#getBoxArtSmall}} has-img{{/getBoxArtSmall}}">');
t.push("{{#getBoxArtSmall}}");
t.push('<img src="{{getBoxArtSmall}}" alt="{{title}}" />');
t.push("{{/getBoxArtSmall}}");
t.push("</div>");
t.push('<div class="description">');
t.push('<p class="title">');
t.push("<strong>{{title}}</strong>");
t.push("{{#hasChildMedia}}<span>{{getChildMedias}}</span>{{/hasChildMedia}}");
t.push("<span>{{#hasRunDates}}{{getRunYears}} |{{/hasRunDates}} {{#hasParentalRating}}{{highestParentalRating}} |{{/hasParentalRating}} {{#categories}}{{title}} {{/categories}}</span>");
t.push("</p>");
t.push("<p>{{description}}</p>");
t.push("</div>");
t.push("{{/mediaGroup}}");
t.push('<div class="grouped-media-items">');
t.push("{{#listings}}");
t.push("{{#isFirstItem}}");
t.push("<ul>");
t.push('<li class="header">');
t.push('<div class="media-title">');
t.push("{{#localizeText}}title{{/localizeText}}");
t.push("</div>");
t.push('<div class="notifications">');
t.push("</div>");
t.push('<div class="channel">');
t.push("{{#localizeText}}channel{{/localizeText}}");
t.push("</div>");
t.push('<div class="air-time">');
t.push("{{#localizeText}}airTime{{/localizeText}}");
t.push("</div>");
t.push("</li>");
t.push("{{/isFirstItem}}");
t.push("{{{hiddenStart}}}");
t.push('<li class="media-item" {{^isMediaGroup}}data-media-entitlements="{{entitlements}}"{{/isMediaGroup}}>');
t.push('<div class="media-title">');
t.push("<p>");
t.push("<strong>{{#program}}{{title}}{{/program}}</strong>");
t.push("<span>{{#seasonNumber}} ({{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}){{/seasonNumber}} {{#getDuration}} ({{getDuration}}){{/getDuration}}</span>");
t.push("</p>");
t.push("</div>");
t.push('<div class="notifications">');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push("</div>");
t.push('<div class="channel">{{channelNumber}} {{stationTitle}}</div>');
t.push('<div class="air-time">{{getFormattedAirDate}}</div>');
t.push("</li>");
t.push("{{{hiddenEnd}}}");
t.push("{{#isLastItem}}");
t.push("</ul>");
t.push("{{#isExpandable}}");
t.push('<div class="show-more">');
t.push('<p><a href="#" data-text-expand="{{#localizeText}}viewAll{{/localizeText}}" data-text-collapse="{{#localizeText}}hideAll{{/localizeText}}"><span class="toggler">{{#localizeText}}viewAll{{/localizeText}}</span> {{groupTitle}} <span class="icon"></span></a></p>');
t.push("</div>");
t.push("{{/isExpandable}}");
t.push("{{/isLastItem}}");
t.push("{{/listings}}");
t.push("</div>");
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").TimeSlot=orion.templates.TimeSlot||(function(){var TimeSlot='{{#times}}<div class="time-slot"> {{display}} </div>{{/times}}';
return TimeSlot
})();
BBV.namespace("orion.templates").TitleCardFeedGridItem=orion.templates.TitleCardFeedGridItem||(function(){var t=[];
t.push('<ul class="grid-view thumbnails">');
t.push("{{#medias}}");
t.push('<li class="grid-item media-item{{#isPlayable}} playable{{/isPlayable}}" data-media-id="{{id}}" {{^isMediaGroup}}data-media-entitlements="{{entitlements}}"{{/isMediaGroup}}>');
t.push('<div class="hover-toggle">');
t.push('<div class="no-hover">');
t.push('<a class="hover-toggle-link {{imageType}}{{#getImg}} has-img{{/getImg}}" href="{{buildMediaUrl}}">');
t.push("{{#getImg}}");
t.push('<img src="{{getImg}}" alt="{{title}}" />');
t.push("{{/getImg}}");
t.push("</a>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}{{^title}}&nbsp;{{/title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#secondaryTitle}}");
t.push('<p class="secondary-title">');
t.push('"{{secondaryTitle}}"');
t.push("</p>");
t.push("{{/secondaryTitle}}");
t.push("{{#isMovie}}");
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push("{{/isMovie}}");
t.push("{{#isEpisode}}");
t.push('<p class="episode-info">');
t.push("{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}");
t.push("</p>");
t.push("{{/isEpisode}}");
t.push("</div>");
t.push('<div class="hover-box">');
t.push('<div class="overlay-toggle">');
t.push('<div class="boxart-wrap">');
t.push('<a class="{{imageType}}{{#getImg}} has-img{{/getImg}}" href="{{buildMediaUrl}}">');
t.push("{{#getImg}}");
t.push('<img src="{{getImg}}" alt="{{title}}" />');
t.push('<div class="play"></div>');
t.push("{{/getImg}}");
t.push("</a>");
t.push('<div class="titlecard-functionality">');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push('<span class="thumbs-down"><a href="#">thumbs down</a></span>');
t.push('<span class="thumbs-up"><a href="#">thumbs up</a></span>');
t.push("</div>");
t.push("</div>");
t.push('<p class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}{{^title}}&nbsp;{{/title}}</a>');
t.push('{{#isTVOD}}<span class="tvod">{{{getCurrency}}}</span>{{/isTVOD}}');
t.push('{{^isMediaGroup}}<span class="locked">locked</span>{{/isMediaGroup}}');
t.push('{{#currentCatchUpCount}}<div class="broadcast-date">{{getEarliestBroadcastDate}}</div>{{/currentCatchUpCount}}');
t.push("</p>");
t.push("{{#secondaryTitle}}");
t.push('<p class="secondary-title">');
t.push('"{{secondaryTitle}}"');
t.push("</p>");
t.push("{{/secondaryTitle}}");
t.push("{{#isMediaGroup}}");
t.push("{{#hasChildMedia}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{/hasChildMedia}}");
t.push("{{#hasRunDates}}");
t.push('<p class="release-date">');
t.push("{{getRunYears}}");
t.push("</p>");
t.push("{{/hasRunDates}}");
t.push("{{/isMediaGroup}}");
t.push("{{#isEpisode}}");
t.push('<p class="episode-info">');
t.push("{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}");
t.push("</p>");
t.push('{{#formatLength}}<p class="run-time">({{formatLength}})</p>{{/formatLength}}');
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push("{{/isEpisode}}");
t.push("{{#isMovieItem}}");
t.push('<p class="episode-info">');
t.push("{{getChildMedias}}");
t.push("</p>");
t.push("{{#year}}");
t.push('<p class="release-date">{{year}}</p>');
t.push("{{/year}}");
t.push("{{/isMovieItem}}");
t.push("{{#hasCategories}}");
t.push('<p class="genre">');
t.push("{{{getGenre}}}");
t.push("</p>");
t.push("{{/hasCategories}}");
t.push("</div>");
t.push("</div>");
t.push("</div>");
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
return t.join("")
})();
BBV.namespace("orion.templates").TitleCardFeedListItem=orion.templates.TitleCardFeedListItem||(function(){var t=[];
t.push('<ul class="list-view">');
t.push('<li class="header">');
t.push('<span class="title">{{#localizeText}}titleheading{{/localizeText}}</span>');
t.push('<span class="rating">{{#localizeText}}ratedheading{{/localizeText}}</span>');
t.push('<span class="genre">{{#localizeText}}genreheading{{/localizeText}}</span>');
t.push('<span class="release-date">{{#localizeText}}releaseheading{{/localizeText}}</span>');
t.push('<span class="add"></span>');
t.push("</li>");
t.push("{{#medias}}");
t.push('<li class="media-item{{#isMediaGroup}} media-group{{/isMediaGroup}}{{#inPlaylist}} in-playlist{{/inPlaylist}}" data-media-id="{{id}}" {{^isMediaGroup}}data-media-entitlements="{{entitlements}}"{{/isMediaGroup}}>');
t.push("{{#title}}");
t.push('<span class="title">');
t.push('<a href="{{buildMediaUrl}}">{{title}}</a> {{#formatLength}}<span class="run-time">({{formatLength}})</span>{{/formatLength}}');
t.push("{{#isEpisode}}");
t.push('<span class="episode-info">');
t.push("{{#seasonNumber}}{{#localizeText}}season{{/localizeText}} {{seasonNumber}}{{/seasonNumber}}{{#seasonEpisodeNumber}} : {{#localizeText}}episode{{/localizeText}} {{seasonEpisodeNumber}}{{/seasonEpisodeNumber}}");
t.push("</span>");
t.push("{{/isEpisode}}");
t.push("</span>");
t.push("{{/title}}");
t.push('<span class="rating">{{highestParentalRating}}</span>');
t.push('<span class="genre">{{{getGenre}}}</span>');
t.push('<span class="release-date">{{getFormattedDate}}</span>');
t.push('<span class="add"><a href="#">+</a></span>');
t.push('<span class="remove"><a href="#">&ndash;</a></span>');
t.push("</li>");
t.push("{{/medias}}");
t.push("</ul>");
return t.join("")
})();
BBV.namespace("orion.templates").TitleCardOffers=orion.templates.TitleCardOffers||(function(){var t=[];
t.push("<ul>");
t.push("{{#offers}}");
t.push("<li>");
t.push("<h4></h4>");
t.push('<span class="button"></span>');
t.push("</li>");
t.push("{{/offers}}");
t.push("</ul>");
return t.join("")
})();
BBV.namespace("orion.templates").TvodDialog=orion.templates.TvodDialog||(function(){return['<div id="tvod-checkout" class="tvod-checkout">',"<header>","<hgroup>","<h1>{{i18n_review_order}}</h1>","<h2>{{i18n_bill_to_account}}</h2>","</hgroup>","</header>",'<div class="order-summary">','<ul class="order-summary-list">',"{{#item}}",'<li class="order-summary-item">','<div class="product-details">','<p class="title">{{title}}</p>','<p class="secondary-title">{{secondary_title}}</p>',"</div>",'<div class="offer-details">','<p class="cost">{{{cost}}}</p>',"<p>{{rental_duration}}</p>","</div>","</li>","{{/item}}","</ul>","</div>","{{#item.isAdult}}",'<form method="" class="dialog-pin-form">','<h1>{{i18n_enter_pin}} <a href="#" class="why-required-link">{{i18n_why_pin_required}}</a></h1>','<fieldset class="pin-settings">','<p class="error"></p>','<div class="field">','<input type="password" name="pin1" maxlength="1" value="" />','<input type="password" name="pin2" maxlength="1" value="" />','<input type="password" name="pin3" maxlength="1" value="" />','<input type="password" name="pin4" maxlength="1" value="" />',"</div>",'<div class="actions">','<p><span class="button tvod-checkout-button"><input type="submit" value="{{i18n_buy_now_button}}" id="buynow" class="checkout-arrow"></span></p>','<p>{{i18n_enter_pin_or}} <a href="#" id="offer-cancel-link">{{i18n_cancel}}</a></p>',"</div>","</fieldset>","</form>","{{/item.isAdult}}","{{^item.isAdult}}",'<form method="" class="dialog-pw-form">','<h1>{{i18n_enter_pw}} <a href="#" class="why-required-link">{{i18n_why_pw_required}}</a></h1>','<fieldset class="pin-settings">','<p class="error"></p>','<div class="field">','<input type="password" name="pw" value="" />',"</div>",'<div class="actions">','<p><span class="button tvod-checkout-button"><input type="submit" value="{{i18n_buy_now_button}}" id="buynow" class="checkout-arrow"></span></p>','<p>{{i18n_enter_pw_or}} <a href="#" id="offer-cancel-link">{{i18n_cancel}}</a></p>',"</div>","</fieldset>","</form>","{{/item.isAdult}}",'<div class="about-rentals">',"<h1>{{i18n_about_rentals_header}}</h1>",'<div class="content">',"<p>{{i18n_about_rentals}}</p>","<p>{{i18n_by_clicking}}</p>","</div>","</div>","</div>"].join("")
})();
BBV.namespace("orion.templates").VideoMessage=orion.templates.VideoMessage||(function(){var t=[];
t.push('<div class="message{{#onLeftSide}} left-side{{/onLeftSide}}">');
t.push('<a href="#" class="close">{{close}}</a>');
t.push("<span></span>");
t.push('<p class="message-body">{{{message}}}</p>');
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").VodPromo=orion.templates.VodPromo||(function(){var t=[];
t.push('<div class="vod-promo">');
t.push('<img src="{{imgSrc}}" alt="{{assetTitle}}"/>');
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").ConfirmationDialog=orion.templates.ConfirmationDialog||(function(){var t=[];
t.push('<div class="inner">');
t.push("<h2>{{title}}</h2>");
t.push("<p>{{body}}</p>");
t.push('<div class="controls">');
t.push('<span class="button confirmation-dialog-button"><a class="confirm" href="#">{{i18nConfirm}}</a></span>');
t.push('<span><a class="cancel" href="#">{{i18nCancel}}</a></span>');
t.push("</div>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").LiveChannels=orion.templates.LiveChannels||(function(){var t=[];
t.push("{{#channels}}");
t.push('<li class="channel-item" id="station-{{stationID}}" data-station-id="{{stationID}}" data-channel-id="{{channelID}}" data-channel-number="{{channelNumber}}" data-entitlements="{{entitlements}}">');
t.push('<a href="{{channelUrl}}" title="{{title}}">');
t.push("{{#stationImg.url}}");
t.push('<img src="{{stationImg.url}}" width="{{stationImg.width}}" height="{{stationImg.height}}" alt="{{title}}" />');
t.push("{{/stationImg.url}}");
t.push("{{^stationImg.url}}");
t.push('<span class="no-logo">{{title}}</span>');
t.push("{{/stationImg.url}}");
t.push("</a>");
t.push('<div class="channel-tooltip" style="display:none"></div>');
t.push("</li>");
t.push("{{/channels}}");
return t.join("")
})();
BBV.namespace("orion.templates").LiveChannelsTooltip=orion.templates.LiveChannelsTooltip||(function(){var t=[];
t.push("{{#title}}");
t.push('<h3 class="title">{{title}}</h3>');
t.push("{{/title}}");
t.push("{{#secondaryTitle}}");
t.push('<h4 class="episode">"{{secondaryTitle}}"</h4>');
t.push("{{/secondaryTitle}}");
t.push('<p class="season">');
t.push("{{#seasonNumber}}");
t.push("{{seasonText}} {{seasonNumber}},");
t.push("{{/seasonNumber}}");
t.push("{{#seasonEpisodeNumber}}");
t.push("{{episodeText}} {{seasonEpisodeNumber}}");
t.push("{{/seasonEpisodeNumber}}");
t.push("</p>");
t.push('<p class="channel-details">{{channelTitle}}, {{duration}}</p>');
t.push("<p>{{description}}</p>");
t.push("{{#nextTitle}}");
t.push('<p class="up-next">{{onnextText}} <span class="show-title">{{nextTitle}}</span>');
t.push("{{#nextDuration}}");
t.push(', <span class="time-range">{{nextDuration}}</span></p>');
t.push("{{/nextDuration}}");
t.push("{{/nextTitle}}");
return t.join("")
})();
BBV.namespace("orion.templates").LiveChannelsTooltipEmpty=orion.templates.LiveChannelsTooltipEmpty||(function(){var t=[];
t.push('<h3 class="title">{{tba_text}}</h3>');
return t.join("")
})();
BBV.namespace("orion.templates").PinChangeDialog=orion.templates.PinChangeDialog||(function(){var tpl=[];
tpl.push('<div class="inner pin-change-confirmation">');
tpl.push("{{#title}}<h3>{{title}}</h3>{{/title}}");
tpl.push("{{#message}}<p>{{message}}</p>{{/message}}");
tpl.push('<div class="controls">');
tpl.push('<span class="button confirmation-dialog-button"><a class="confirm" href="#">{{i18nConfirm}}</a></span>');
tpl.push('<span><a class="cancel" href="#">{{i18nCancel}}</a></span>');
tpl.push("</div>");
tpl.push("</div>");
return tpl.join("")
})();
BBV.namespace("orion.templates").MiniVideoPlayerError=orion.templates.MiniVideoPlayerError||(function(){var t=[];
t.push('<div class="mini-player-error">');
t.push('<div class="error">');
t.push("<h2>{{heading}}</h2>");
t.push("<p>{{message}}</p>");
t.push("</div>");
t.push("</div>");
return t.join("")
})();
BBV.namespace("orion.templates").ChannelCard=orion.templates.ChannelCard||(function(){return["<header>",'<h1 class="channel-title">{{title}}</h1>',"</header>",'<div class="section">','<ul class="tabs">','<li id="tab-overview" class="tab active">','<a href="#overview"{{#background}} style="background:{{background}}"{{/background}}>{{i18nChannelCard.overviewText}}</a>',"</li>",'<li id="tab-guide" class="tab">','<a href="#guide">{{i18nChannelCard.tvGuideTabText}}</a>',"</li>","</ul>",'<div id="overview" class="section">',"{{#logo}}",'<img id="station-logo" class="left" src="{{logo.url}}" width="{{logo.width}}" height="{{logo.height}}" />',"{{/logo}}",'<h2>{{i18nChannelCard.titlePreText}} <span class="channel-title">{{title}}</span></h2>','<div class="fb-like" data-href="{{fbLinkUrl}}" data-send="false" data-width="450" data-show-faces="false" data-asset-name="{{title}}" data-colorscheme="light" data-asset-id="{{channelId}}"></div>','<p class="channel-description">{{description}}</p>',"</div>",'<div id="guide" class="section" style="display: none;">','<a href="{{tvGuidePath}}" class="epg-link">{{i18nChannelCard.epgLinkText}}</a>','<div class="section content-list">','<div class="listing-container" ','data-page-size="10" ','data-template="CardListings" ','data-enable-paging="true" ','data-listing-url="{{routes.listings}}?byStationId={{stationId}}&sort=startTime" ','data-isLive="{{hasLiveStream}}" ','data-title="{{title}}" ','data-i18n-property="channelCardListing">',"</div>","</div>","</div>","</div>",'<div class="section content-list most-popular{{^providerId}} hidden{{/providerId}}"','{{#providerId}} data-feed-url="{{routes.mediagroups}}?byProviderId={{providerId}}&sort=playCount|desc&range=1-5"{{/providerId}}>','<h2>{{i18nChannelCard.popPreText}} <span class="channel-title"></span></h2>','<div class="feed-container" ','data-feed-url="{{dataFeedUrl}}" ','data-i18n-property="channelCardFeed">',"</div>","</div>"].join("")
})();
